name: Access Log

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Keeps manual trigger with date input
    inputs:
      date:
        description: "Date to run the script for"
        required: true
        default: "2025-06-25"

jobs:
  accesses:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r .github/scripts/ncar-access-log/requirements.txt

      - name: Force disable debug
        run: echo "Debug off"
        env:
          ACTIONS_STEP_DEBUG: false
          ACTIONS_RUNNER_DEBUG: false

      - name: Run access log script
        run: python .github/scripts/ncar-access-log/main.py --date ${{ github.event.inputs.date }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Compress access logx with xz
        run: |
          find . -type f -name '*.log' -exec xz -9 -T0 {} \;

      - name: Commit changes
        run: |
          git add .
          git commit -m "Add backfilled daily access logs" || echo "No changes to commit"

      - name: Pull with rebase and push
        run: |
          for i in {1..5}; do
            git pull --rebase origin ${{ github.ref_name }} && \
            git push origin ${{ github.ref_name }} && break
            echo "Retrying push after 5 seconds..."
            sleep 5
          done

      - name: Cleanup after job
        run: |
          rm -rf logs/ temp/ *utc.log
          df -h